services:
  house-rnv:
    build: HouseSimulator/
    ports:
      - "5053:5050"
  house-tka:
    build: HouseSimulator/
    ports:
      - "5052:5050"
  house-cmu:
    build: HouseSimulator/
    ports:
      - "5051:5050"
  house-mse:
    build: HouseSimulator/
    ports:
      - "5050:5050"