name: Deploy Backend to Cybera

on:
  workflow_run: 
    workflows: ["Gradle Test"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Cybera
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - uses: actions/checkout@v4
      - name: Remove .git to prevent access issue
        run: |
          rm -rf .git
        shell: bash

      - name: Copy to Cybera
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "."
          target: "~/prod"
          overwrite: true

      - name: Restart Cybera Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            cd ~/prod/smart-home

            docker tag smart-home-platform:active smart-home-platform:prev
            docker tag smart-home-mysql-container:active smart-home-mysql-container:prev 

            docker compose -f docker-compose-backend.yml up --build -d
