name: Gradle Test

on:
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Gradle Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build Gradle
        working-directory: "smart-home/Platform"
        run: |
          chmod +x gradlew
          ./gradlew build --exclude-task test
  gradle-test:
    name: Gradle Test
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Run Tests
        working-directory: "smart-home/Platform"
        run: |
          chmod +x gradlew
          ./gradlew test
      - name: Jacoco report
        working-directory: "smart-home/Platform"
        run: ./gradlew jacocoTestCoverageVerification
  deploy:
    name: Deploy to Cybera
    runs-on: self-hosted
    needs: gradle-test

    steps:
      - uses: actions/checkout@v4
      - name: Remove .git to prevent access issue
        run: |
          rm -rf .git
        shell: bash

      - name: Copy to Cybera
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "."
          target: "~/prod"
          overwrite: true

      - name: Restart Cybera Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            cd ~/prod
            docker compose down
            docker compose up --build -d
