name: Gradle Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Gradle Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build Gradle
        working-directory: "smart-home/Platform"
        run: |
          chmod +x gradlew
          ./gradlew build --exclude-task test
  gradle-test:
    name: Gradle Test
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Run Tests
        working-directory: "smart-home/Platform"
        run: |
          chmod +x gradlew
          ./gradlew test
      - name: Jacoco report
        working-directory: "smart-home/Platform"
        run: ./gradlew jacocoTestCoverageVerification
